### ISSUE TITLE
errors happend during the loading process of pretrained detr-r50-e632da11.pth

### ISSUE THREAD

**Issue by LANMNG** [ZhanYang-nwpu/RSVG-pytorch#13]
Traceback (most recent call last):                                                                           
  File "main.py", line 541, in <module>                                                                      
    main()                                                                                                   
  File "main.py", line 170, in main                                                               
    model = load_pretrain(model, args, logging) 
  File "/data/users/lanmeng/projects/RSVG/utils/checkpoint.py", line 20, in load_pretrain        
    pretrained_dict = checkpoint['state_dict']
KeyError: 'state_dict'

**Comment by aghand0ur** [comment]
Hello @LANMNG 
We are getting the same error
can you please let me know how you solve it?

cc @Hasanmog @Louma20
